filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/app/logs/application.json
processors:
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "log.offset", "version"]
output.logstash:
  hosts: ["IP:5044"]
